### PR TITLE
Failing to compile when show_author true

### PR DESCRIPTION
**Pull request by abhikjain360**
Fails to compile when `show_author = true` in the `config.toml` file. This (maybe ?) fixes it.

### CODE REVIEW

**Comment by ejmg** [comment]
hey thanks for the PR.

hmm. it looks like the vercel auto-deployments don't work anymore and without further context i can't take this PR yet. i'll look into the issue when i have a chance.

**Comment by djacu** [comment]
I just started using this repo, found this exact same bug, and implemented the same fix independently. It seems like vercel is working unless I'm not understanding what the bot is doing.

**Comment by ejmg** [comment]
unfortunately, i've left a few of these PR's fall through the crack. apologies for not getting your work in sooner, @abhikjain360.

**Comment by ejmg** [comment]
> 



> I just started using this repo, found this exact same bug, and implemented the same fix independently. It seems like vercel is working unless I'm not understanding what the bot is doing.

really sorry about that @djacu. whatever the reason, vercel didn't deploy on this PR the first time it was put up and i let that stop me from testing/merging abhikjain360's work.

**Comment by djacu** [comment]
No worries @ejmg! It was a good learning experience for me and glad it was able to be resolved. Thanks for returning to the PR and making this theme! :)

**Pull request merged**
