### PR TITLE
Update Vercel Deployment to Zola v0.15.3

### PR DESCRIPTION
**Pull request by maydayv7**

### CODE REVIEW

**Comment by maydayv7** [comment]
This is an open issue:
* https://github.com/getzola/zola/issues/1713
* https://community.cloudflare.com/t/cloudflare-pages-zola-build-fails-glibcxx-3-4-26-not-found/316457

**Comment by maydayv7** [comment]
A quick dirty fix to get #53 to work would be to just upgrade Zola to v0.14.0 instead of the latest version

**Comment by DesmondWillowbrook** [comment]
If I'm reading the documentation right, it seems that we [can't change the build image](https://vercel.com/docs/concepts/deployments/build-step#build-image). Instead, what we _can_ do is build Zola from source, since Vercel does give an option to install Rust.

**Comment by ejmg** [comment]
man, it looks like keats got zola v0.15.3 working for his website using netflify. if changing the entire deployment setup turns out to be simpler, then maybe we should consider that too.

**Comment by DesmondWillowbrook** [comment]
Any update?

**Comment by ejmg** [comment]
unfortunately, no.

i haven't made the time to setup either a separate deployment mechanism (as i previously mentioned) or see how vercel can be made to work with a patch/work-around.

**Comment by ejmg** [comment]
i've knocked out a few PR's this past week, i will try to follow up on this one along with a few others.

**Pull request closed without merging**
